
name: Build Custom Packer Docker Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/rexonix-infra/lab-packer:latest

jobs:
  docker-build-push:
    runs-on: [self-hosted, linux, initial, rexonix-infra]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
